mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('study_buddy_app/', include('study_buddy_app.urls')),
    path('admin/', admin.site.urls),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]

study_buddy_app/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('searchResults/', views.SearchResultsView.as_view(), name='search_results'),
    path('home/', views.home, name='home'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path("accounts/", include("allauth.urls")),
    path('logout', LogoutView.as_view(), name='logout'),

    path('deptlist/', views.deptlist, name="deptlist"),
    path('deptdisplay/<str:dept_name>/', views.dept_display_only, name="deptdisplay"),
    path('deptdisplay/<str:dept_name>/classlookup/', views.class_lookup, name="classlookup"),
    
    path('home/<str:room>/', views.room, name='room'),
    path('home/go_to_chat', views.go_to_chat, name='go_to_chat'),
    path('home/checkview', views.checkview, name='checkview'),
    path('home/send', views.send, name='send'),
    path('home/getMessages/<str:room>', views.getMessages, name='getMessages'),
    
    path('user/', views.user, name='user'),
    path('user/edituser/', views.edituser, name='edituser'),

    path('publicProfile/', views.publicProfile, name='publicProfile'),

    path('publicProfile/user_redirect/', views.user_redirect, name='user_redirect'),

    path('publicProfile/<slug:slug>/', views.ProfileDetail.as_view(), name='profile-detail'),
    path('publicProfile/<slug:slug>/success', views.ProfileDetailSuccess.as_view(), name="profile-detail-success"),
    path('user/friends/publicProfile/<slug:slug>/', views.ProfileDetail.as_view(), name='profile-detail'),
    path('user/friend_request/publicProfile/<slug:slug>/', views.ProfileDetail.as_view(), name='profile-detail'),


    path('publicProfile/<slug:slug>/study_buddy_app/send_friend_request/', views.send_friend_request,name='send friend request'),
    
    #path('user/friends/', views.viewFriends.as_view(), name='new_friends'),
    path('user/friends/', views.viewFriends, name='new_friends'),
    path('user/friends/remove_friend/<str:pk>/', views.remove_friend, name='remove_friend'),

    #path('user/friend_request/', views.viewRequest.as_view(), name='requests'),
    path('user/friend_request/', views.viewRequest, name='requests'),
    path('user/friend_request/delete_request/<str:pk>/', views.delete_request, name='delete_request'),

    path('user/friend_request/accept_friend_request/<str:pk>/', views.accept_friend_request, name='accept friend request'),


    path('user/deptlist/', views.addclass_deptlist, name="addclass_deptlist"),
    path('user/dept/<str:dept_name>/', views.dept, name="dept"),
    path('user/addclass', views.addclass, name="addclass"),
    path('user/deleteclass/', views.myclasses, name="myclasses"),
    path('user/dc', views.deleteclass, name="deleteclass"),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
]

study_buddy_app/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.dispatch import receiver #add this
from django.db.models.signals import post_save #add this
from django.template.defaultfilters import slugify  # new

class Room(models.Model):
    name = models.CharField(max_length=1000)
class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)

class Class(models.Model):
    subject = models.CharField(max_length=4)
    catalog_number = models.CharField(max_length=4)
    course_section = models.CharField(max_length=3)
    def __str__(self):
        return self.subject + " " + self.catalog_number + " -- Section " + self.course_section

class Profile(models.Model):  # add this class and the following fields
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    classes = models.ManyToManyField(Class)
    slug = models.SlugField(unique=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = self.user.username
        super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.user)

    @receiver(post_save, sender=User)  # add this
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)  # add this
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Friends1(models.Model):
    users1 = models.ManyToManyField(User, null=True)
    current_user = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE,null=True)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend,create=cls.objects.get_or_create(current_user=current_user)
        friend.users1.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, create = cls.objects.get_or_create(current_user=current_user)
        friend.users1.remove(new_friend)


class FriendRequest(models.Model):
    sender=models.ForeignKey(User,null=True,related_name='sender1',on_delete=models.CASCADE)
    receiver=models.ForeignKey(User,null=True,on_delete=models.CASCADE)

##class User(AbstractUser):
##    friends = models.ManyToManyField("User", blank=True)
##
##class Friend_Request(models.Model):
##    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
##    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
##

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    users = models.ManyToManyField(User)
    def __str__(self):
        return str(self.title)+" "+str(self.start_time)+" "+str(self.end_time)

study_buddy_app/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name', 'last_name', 'email', 'id')

study_buddy_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from study_buddy_app.models import Room, Message, Profile
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.paginator import Paginator

from django.db.models import Q # new
from django.views import generic
from django.urls import reverse
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin
from django.views import View

from django.shortcuts import render
import requests
from django import template

register = template.Library()
from .models import Profile, Class
from .forms import UserForm
from django import forms
from .models import Friends1
from .models import FriendRequest
#from .models import Class
from django.views import generic
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from allauth.socialaccount.models import SocialToken, SocialApp, SocialAccount

from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from django.contrib import messages
from .models import *
from .utils import Calendar
from datetime import datetime
from pytz import timezone
from allauth.socialaccount.models import SocialAccount
import re
class SearchResultsView(generic.ListView):
    template_name = 'study_buddy_app/searchResults.html'
    context_object_name = 'search_results_list'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            template = loader.get_template('socialaccount/login.html')
            context = {}
            return redirect('/study_buddy_app/accounts/google/login/')
        return super(SearchResultsView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        """Return all the users."""
        query = self.request.GET.get("q")
        User = get_user_model()
        # search based on username
        users = User.objects.filter(Q(username__iexact=query) | Q(username__iexact=query))
        cardResults = []
        if not query or query is "":
            combination = zip(users, cardResults) 
            return {'combination': combination, 'user': self.request.user}
        #search based on first name
        users |= User.objects.filter(Q(first_name__iexact=query) | Q(first_name__iexact=query))

        # search based on last name only
        users |= User.objects.filter(Q(last_name__iexact=query) | Q(last_name__iexact=query))

        #search based on first and last name
        copy = query
        firstLastArr = copy.split(' ', 2)
        if len(firstLastArr) > 1: 
            users |= User.objects.filter(Q(first_name__iexact=firstLastArr[0]) & Q(last_name__iexact=firstLastArr[1]))


        # searcj based on class
        def has_numbers(inputString):
            return any(char.isdigit() for char in inputString)
        flag1 = not query is None and not has_numbers(query)
        flag2 = not query is None and has_numbers(query)
        flag3 = not query is None and has_numbers(query[0])

        if flag1:
            users |= User.objects.filter(Q(profile__classes__subject__iexact=query))

        if flag2 and not flag3:
            copy = query
            copy = copy.replace(" ", "")
            temp = re.compile("([a-zA-Z]+)([0-9]+)")
            arr = temp.match(copy).groups()
            if len(arr) == 2:
                users |= User.objects.filter(Q(profile__classes__subject__iexact=arr[0]) & Q(profile__classes__catalog_number__iexact=arr[1]))
        users = users.distinct()
        for user in users: 
            if flag1:
                cardResults.append(user.profile.classes.all().filter(Q(subject__iexact=query)))
            if flag2:
                cardResults.append(user.profile.classes.all().filter(Q(subject__iexact=arr[0]) & Q(catalog_number__iexact=arr[1])))
        combination = zip(users, cardResults)
        return {'combination': combination, 'user': self.request.user}
    
    


def index(request):
    template = loader.get_template('study_buddy_app/home.html')
    context = {}
    return HttpResponse(template.render(context, request))


def sign_in(request):
    template = loader.get_template('study_buddy_app/google_login.html')
    context = {}
    return HttpResponse(template.render(context, request))
def home(request):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    User = get_user_model()
    users = User.objects.all()
    object = Friends1.objects.filter(users1=request.user)
    return render(request, 'study_buddy_app/chat.html', {'user_firstname': request.user.first_name, 'user_lastname': request.user.last_name,'users': users, "friend_list": object})

# addclass API
def addclass_deptlist(request):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    response = requests.get('http://luthers-list.herokuapp.com/api/deptlist/?format=json').json()
    paginator = Paginator(response, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'study_buddy_app/addclassdeptlist.html', {'first': request.user.first_name,'last': request.user.last_name,'response':response, 'page_obj': page_obj})
# "
def dept(request, dept_name):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    classes = requests.get('http://luthers-list.herokuapp.com/api/dept/%s?format=json' %dept_name)
    response = classes.json()
    cur_classes = []
    for i in response:
        tmp = Class(subject=dept_name, catalog_number=i['catalog_number'], course_section=i['course_section'])
        tmp.save()
        cur_classes.append(tmp)
    return render(request, 'study_buddy_app/dept.html', {"first": request.user.first_name, "last": request.user.last_name, 'response':cur_classes, 'dept_name':dept_name})

# deleteclass API
def myclasses(request):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    profile = Profile.objects.get(user=request.user)
    classes = profile.classes.all()
    return render(request = request, template_name ="study_buddy_app/deleteclass.html", context = {"user":request.user, 'classes':classes})

# display only API
def deptlist(request):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    response = requests.get('http://luthers-list.herokuapp.com/api/deptlist/?format=json').json()
    paginator = Paginator(response, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'study_buddy_app/deptlist.html', {"first": request.user.first_name, "last": request.user.last_name, 'response': response, 'page_obj': page_obj})

# "
def dept_display_only(request, dept_name):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    classes = requests.get('http://luthers-list.herokuapp.com/api/dept/%s?format=json' %dept_name)
    response = classes.json()
    cur_classes = []
    for i in response:
        tmp = Class(subject=dept_name, catalog_number=i['catalog_number'], course_section=i['course_section'])
        tmp.save()
        cur_classes.append(tmp)
    paginator = Paginator(response, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'study_buddy_app/deptdisplay.html', {'response':cur_classes, 'dept_name':dept_name, 'page_obj': page_obj})

def room(request, room):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    username = request.GET.get('username')
    room_details = Room.objects.get(name=room)
    return render(request, 'study_buddy_app/room.html', {
        'first': request.user.first_name,
        'last': request.user.last_name,
        'username': username,
        'room': room,
        'room_details': room_details
    })

def go_to_chat(request):
    if not request.user.is_authenticated:
        template = loader.get_template('socialaccount/login.html')
        context = {}
        return redirect('/study_buddy_app/accounts/google/login/')
    sender = request.user.username + " "
    sendee = request.POST['username'] + " "
    array = [sender, sendee]
    array.sort()
    room = ""


    array.sort()

    array[-1] = array[-1].strip(" ")

    for i in array:
        room = room + i

    object = Friends1.objects.filter(users1=request.user)

    friends = []

    for i in object:
        friends.append(str(i.current_user))
    print(friends)

    system_messages = messages.get_messages(request)
    for message in system_messages:
        # This iteration is necessary
        pass

    sendee = sendee.strip(" ")
    if str(sendee) not in friends:
        messages.success(request, "You are not friends with this person! Add them as a friend to chat with them again!")

study_buddy_app/templates/study_buddy_app/Nav_Calendar.html
{% url 'index' as homepage %}
{% url 'home' as chatpage %}
{% url 'deptlist' as course_list %}
{% url 'calendar' as calendar %}
{% url 'user' as personal_profile %}
{% url 'new_friends' as friends_page %}
{% url 'logout' as logout %}
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <!-- <script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            clifford: '#da373d',
          }
        }
      }
    }
  </script> -->
</head>
<body>
    <nav class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
          <div class="relative flex h-16 items-center justify-between">
            <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
              <!-- Mobile menu button-->
              <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <!--
                  Icon when menu is closed.
      
                  Heroicon name: outline/bars-3
      
                  Menu open: "hidden", Menu closed: "block"
                -->
                <svg class="block h-6 w-6" xmlns="../static/study_buddy_app/images/LogoReal" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
                <!--
                  Icon when menu is open.
      
                  Heroicon name: outline/x-mark
      
                  Menu open: "block", Menu closed: "hidden"
                -->
                <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
              <div class="flex flex-shrink-0 items-center">
                <img class="block h-10 w-auto lg:hidden" src="https://pixy.org/download/5752755/" alt="Your Company">
                <img class="hidden h-10 w-auto lg:block" src="https://pixy.org/download/5752755/" alt="Your Company">
              </div>
              <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                  <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                  <a href="{{ homepage }}" style= "text-decoration: none;" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Home</a>
      
                  <a href="{{ chatpage }}" style= "text-decoration: none;" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Chat</a>
      
                  <a href="{{ course_list }}" style= "text-decoration: none;" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Course List</a>

                  <a href="{{ calendar }}" style= "text-decoration: none;" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a>

                </div>
              </div>
            </div>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'search_results' %}" method="get" role="search">
              <input name="q" type="search" class="form-control" placeholder="Search name or class..." aria-label="Search">
            </form>
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
      
              <div class="dropdown">
                <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item-text"><b>{{ first }} {{last}}</b></a>
                  <a class="dropdown-item" href="{{ personal_profile }}">Profile</a>
                  <a class="dropdown-item" href="{{ friends_page }}">Friends</a>
                  <a class="dropdown-item" href="{{ logout }}">Logout</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      
      </nav>
      {% if header != ""%}
      <header class="bg-white shadow">
        <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
          <h1 class="text-3xl font-bold tracking-tight text-gray-900">{{ header }}</h1>
        </div>
      </header>
      {% endif %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

study_buddy_app/templates/study_buddy_app/addclassdeptlist.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html>
<head>
    <title>UVA Departments</title>
</head>

{% if user.is_authenticated %}
<header>
    <!-- Navbar -->
    <!-- <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(0, 0, 0, 0.1);">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/home/">Chat</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/deptlist/">Course List</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/user/">User Info</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/searchResults/">Search Users</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/calendar/">Calendar</a>
            </li>
          </ul>
        </div>
      </div>
    </nav> -->
    {% include 'study_buddy_app/Nav_None.html' with first=first last=last header="Add Class"%}
  </header>

{% else %}
<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(0, 0, 0, 0.1);">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarExample01"
        aria-controls="navbarExample01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/study_buddy_app/">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/study_buddy_app/deptlist/">Course List</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
{% endif %}

<body class="d-flex flex-column min-vh-100">
  <!-- <h1 class="text-center">UVA Departments</h1> -->
  <br>
  <h5 class="text-center">Select a department to view classes within it</h5>
  <br>

  <!-- List of classes -->
  <div class="list-group gap-2 col-2 mx-auto">
    {% for dept in page_obj %}
      <a href="/study_buddy_app/user/dept/{{ dept.subject }}" class="text-center list-group-item list-group-item-action list-group-item-primary">{{dept.subject}}</a>
    {% endfor %}
  </div>

  <!-- Pagination -->
  <br>
  <nav aria-label="deptlist paginator">
    <ul class="pagination justify-content-center">
      {% for pg in page_obj.paginator %}
        <li class="page-item"><a class="page-link" href="?page={{ pg.number }}">{{ pg.number }}</a></li>
      {% endfor %}
    </ul>
  </nav>
  <nav aria-label="current page indicator">
    <ul class="pagination justify-content-center">
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
      </li>
    </ul>
  </nav>
</body>

<footer class="text-center text-lg-start bg-light text-muted mt-auto">
    <div class="text-center p-3 me-5 d-none d-lg-block">
      <span>Page Authors: Ana Borges, Bao Nguyen, Evan Tierney, Natasha Mathew, and Holden Present</span>
    </div>
  <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright: None
  </div>
</footer>


</html>

study_buddy_app/templates/study_buddy_app/listProfiles.html
{% load socialaccount %}
{% load crispy_forms_tags %}
{% load ratings %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% if user.is_authenticated %}
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(0, 0, 0, 0.1);">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/home/">Chat</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/deptlist/">Course List</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/user/">User Info</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/searchResults/">Search Users</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/study_buddy_app/calendar/">Calendar</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</header>

<body class="d-flex flex-column min-vh-100">
    <div class="text-center" style="margin-top: 2%;">
    {% for deepthought in profile_list %}
    <p>{{ deepthought.user }}</p>

        <form id="post-form" method="POST" action="/study_buddy_app/publicProfile/user_redirect/">
            {% csrf_token %}
            <input type="hidden" name="username" id="username" value="{{deepthought.user}}"/>
            <input type="submit" value="Send">
        </form>
    {% endfor %}
    </div>
</body>

<footer class="text-center text-lg-start bg-light text-muted mt-auto">
    <div class="text-center p-3 me-5 d-none d-lg-block">
      <span>Page Authors: Ana Borges, Bao Nguyen, Evan Tierney, Natasha Mathew, and Holden Present</span>
    </div>
  <div class="text-center p-2" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2022 Copyright: None
  </div>
</footer>

{% else %}
<div class="text-center" style="margin-top: 2%;">
    <p>Not logged in</p>

    <form action="/study_buddy_app/sign_in/">
      <input type="submit" value="Sign In" />
    </form>
</div>
{% endif %}